inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb

Metrics/AbcSize:
  Exclude:
    - lib/junk_drawer/rails/bulk_updatable.rb

Metrics/BlockLength:
  Exclude:
    - junk_drawer.gemspec
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - lib/junk_drawer/rails/bulk_updatable.rb

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/AnyInstance: { Enabled: false } # broken, re-enable after upgrade
RSpec/DescribeClass: { Enabled: false } # broken, re-enable after upgrade

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  IgnoreMethods: true
  Exclude:
    - spec/junk_drawer/rails/bulk_updatable_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

# non-conventional rules
Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'

Style/LambdaCall:
  EnforcedStyle: braces

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
